# Generated by Django 4.2.1 on 2023-05-06 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replaced_minute', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='football.match')),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, related_name='replacement_as_1', to='football.player')),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, related_name='replacement_as_2', to='football.player')),
            ],
            options={
                'verbose_name': 'Replacement',
                'verbose_name_plural': 'Replacements',
            },
        ),
    ]
