# Generated by Django 4.2.1 on 2023-05-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_match_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.ManyToManyField(related_name='matches', to='football.referee'),
        ),
    ]
