# Generated by Django 4.2.1 on 2023-05-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_back_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='back_up',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(unique=True, verbose_name='Phone number'),
        ),
    ]
